  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mariadb://localhost:3306/sacco_solution
    username: root
    password:
    driverClassName: org.mariadb.jdbc.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost
